### PR TITLE
add node and service announcements

### PR DESCRIPTION
**Pull request by bakins**
Add 2 additional "modes":
- node announcement. to announce the base "node"
- service announcement. to announce the service

These can be used in place of "raw" etcdctl to endure consistency.

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/queensland/6)

### CODE REVIEW

**Comment by bakins** [comment]
Need to update README

**Comment by bakins** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/queensland/6)

---

a bunch of command line options...

---

**Comment by mmlb** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/queensland/6)

---

<sup>**[announce.go, line 5 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-Jhtw6iqluaHxHgwXVNC)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/announce.go#L5)):</sup>
change over to logrus now or via other card?

---

<sup>**[announce.go, line 33 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-JhtvoYtEEHrHZU3xZTp)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/announce.go#L33)):</sup>
add fields with given announcettls and interval?

---

<sup>**[announce.go, line 63 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-JhtwNkFEj4KYk2Vv75P)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/announce.go#L63)):</sup>
I think we should use path.Join, filepath will use \ if queensland is ever run in windows

---

<sup>**[announce.go, line 74 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-JhtwiwjaM8yfE8VCeUT)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/announce.go#L74)):</sup>
todone

---

<sup>**[announce.go, line 83 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-Jhtwf9vr67D1ew_bdo0)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/announce.go#L83)):</sup>
hmm, I vote ttl decides.

---

<sup>**[main.go, line 44 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-JhtwsJOySWzKLef_jI0)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/main.go#L44)):</sup>
lol, I thought you didn't like global vars ;)

---

<sup>**[main.go, line 64 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-JhtzH2GhSmYODnuqZIr)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/main.go#L64)):</sup>
short flags are weird, maybe -D -H -d? Doesn't really seem any better though.

---

<sup>**[README.md, line 13 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-Jhu-9SlYfRZuVftCsHh)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/README.md#L13)):</sup>
use _ or _, so it looks like _helpers_ or *helpers_, which stand out better in the rendered pages.

---

<sup>**[README.md, line 39 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-Jhu-LSR2SiXhueTVMeD)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/README.md#L39)):</sup>
ditto

---

<sup>**[README.md, line 58 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-Jhu-ak_RdGgjOrQE0Tu)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/README.md#L58)):</sup>
I wonder if this should be first or all? lochness guests will only have one ip but queensland clients may not...?

---

<sup>**[README.md, line 201 [r4]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-Jhu6ps-hYFVfWjdHW0C)** ([raw file](https://github.com/mistifyio/queensland/blob/434012ebd87baa9698b434b20680cbf1e49f5e57/README.md#L201)):</sup>
should probably add a comment with filename.

---

<sup>**[README.md, line 220 [r4]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-Jhu6lvgxCLNT-j7a6Lb)** ([raw file](https://github.com/mistifyio/queensland/blob/434012ebd87baa9698b434b20680cbf1e49f5e57/README.md#L220)):</sup>
add .service suffix, don't think it's required but the norm

---

<sup>**[server.go, line 26 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-Jhu2CQxp431KjyXjY0R)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/server.go#L26)):</sup>
little lower you use &dns.Msg{}, should use only 1. Personally I prefer &dns.Msg{}.

---

<sup>**[server.go, line 50 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-Jhu1PnVn26ld8txlKji)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/server.go#L50)):</sup>
when is not having an ip address not an error?

---

**Comment by bakins** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/queensland/6)

---

<sup>**[announce.go, line 5 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-Jhtw6iqluaHxHgwXVNC)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/announce.go#L5)):</sup>
change after this PR, I think. changing enough already ;)

---

<sup>**[announce.go, line 33 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-JhtvoYtEEHrHZU3xZTp)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/announce.go#L33)):</sup>
Add fields to serviceAnnouncement struct?

---

<sup>**[announce.go, line 63 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-JhtwNkFEj4KYk2Vv75P)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/announce.go#L63)):</sup>
good point. fixed.

---

<sup>**[announce.go, line 74 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-JhtwiwjaM8yfE8VCeUT)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/announce.go#L74)):</sup>
:) fixed.

---

<sup>**[announce.go, line 83 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-Jhtwf9vr67D1ew_bdo0)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/announce.go#L83)):</sup>
Maybe have a cli flag for other behavior?

---

<sup>**[main.go, line 44 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-JhtwsJOySWzKLef_jI0)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/main.go#L44)):</sup>
sigh - unfortunately most of the cli packages sorta force them on you :(

---

<sup>**[main.go, line 64 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-JhtzH2GhSmYODnuqZIr)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/main.go#L64)):</sup>
Yeah - I considered not having short flags for some of these. I've never been a fan of having "d" mean one thing and "D" being something completely different.

---

<sup>**[README.md, line 13 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-Jhu-9SlYfRZuVftCsHh)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/README.md#L13)):</sup>
fixed

---

<sup>**[README.md, line 58 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-Jhu-ak_RdGgjOrQE0Tu)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/README.md#L58)):</sup>
is first. I think if you want different behavior, then you should set via cli option - or send a PR ;)

---

<sup>**[README.md, line 201 [r4]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-Jhu6ps-hYFVfWjdHW0C)** ([raw file](https://github.com/mistifyio/queensland/blob/434012ebd87baa9698b434b20680cbf1e49f5e57/README.md#L201)):</sup>
fixed

---

<sup>**[README.md, line 220 [r4]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-Jhu6lvgxCLNT-j7a6Lb)** ([raw file](https://github.com/mistifyio/queensland/blob/434012ebd87baa9698b434b20680cbf1e49f5e57/README.md#L220)):</sup>
good catch. oversight on my part. fixed.

---

<sup>**[server.go, line 26 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-Jhu2CQxp431KjyXjY0R)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/server.go#L26)):</sup>
agreed. I think this was a bad copy paste from an example I kept around. fixed.

---

<sup>**[server.go, line 50 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-Jhu1PnVn26ld8txlKji)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/server.go#L50)):</sup>
well, I was thinking it should halt an entire response because someone had one bad (or incomplete) entry bcs of a misbehaving script or something. added logging here.

---

**Comment by bakins** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/queensland/6)

---

<sup>**[README.md, line 39 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-Jhu-LSR2SiXhueTVMeD)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/README.md#L39)):</sup>
fixed

---

**Comment by mmlb** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/queensland/6)

Reviewed files:
- announce.go @ r5
- main.go @ r6
- node.go @ r1
- README.md @ r5
- server.go @ r5
- util.go @ r1

---

<sup>**[announce.go, line 33 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-JhtvoYtEEHrHZU3xZTp)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/announce.go#L33)):</sup>
nope, I mean logrus.Fields

---

<sup>**[main.go, line 44 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-JhtwsJOySWzKLef_jI0)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/main.go#L44)):</sup>
yeah, the alternative is Run: a closure that calls realRun that has args, but pretty much just as bad

---

<sup>**[README.md, line 58 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-Jhu-ak_RdGgjOrQE0Tu)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/README.md#L58)):</sup>
fair enough

---

**Comment by bakins** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/queensland/6)

---

<sup>**[announce.go, line 33 [r3]](https://reviewable.io:443/reviews/mistifyio/queensland/6#-JhtvoYtEEHrHZU3xZTp)** ([raw file](https://github.com/mistifyio/queensland/blob/503dbd2e6a89ba89fa461ae9460c9bde4ef0b10c/announce.go#L33)):</sup>
gotcha, will do when with to logrus

---

**Pull request merged**
